# Generated by Django 3.2.4 on 2021-06-11 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_pokemon_1', models.PositiveIntegerField(default=0)),
                ('id_pokemon_2', models.PositiveIntegerField(default=0)),
                ('id_pokemon_3', models.PositiveIntegerField(default=0)),
                ('id_pokemon_4', models.PositiveIntegerField(default=0)),
                ('id_pokemon_5', models.PositiveIntegerField(default=0)),
                ('id_pokemon_6', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
